
version: 2
updates:
# Enable version updates for Github Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/build_portDNN_action/action.yml"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"
